### PR TITLE
Fix #144

### LINKED ISSUE #144: [eventually-postgres] subscribers drop connection and then hang
**Describe the bug**
Occasionally subscribers fail here
https://github.com/eventually-rs/eventually-rs/blob/718d9acc473cf731276aec67e6148b163073a7dc/eventually-postgres/src/subscriber.rs#L82

with simply a logged statement
```
2020-12-04T10:44:00.727548992Z thread 'actix-rt:worker:0' panicked at 'subscriber connection failed: Error { kind: Closed, cause: None }', /usr/local/cargo/git/checkouts/eventually-rs-937be219cd9e869e/718d9ac/eventually-postgres/src/subscriber.rs:82:35
```

This would be OK if the process driving an inmemory projection somehow also failed, as that is part of the public API visible to the users of the library. Then the whole thing can be handled in some way or another. However right now if a `projector` is created as follows, then no error or panic is seen, simply the error is getting logged from the `subscriber`, and projection stops working.
```rust
    let dsn = std::env::var("EVENTUALLY_URL").expect("Eventually url not set");
    let subscriber =
        EventSubscriber::<my_aggregate::Id, my_aggregate::MyEvent>::new(&dsn, EVENTUALLY_NAME)
            .await?;
    let subscription = TransientSubscription::new(eventstore.clone(), subscriber);
    let projection = Arc::new(RwLock::new(MyProjection::default()));
    let mut projector = eventually::Projector::new(projection.clone(), subscription);
    eventually::spawn(async move {
        projector
            .run()
            .await
            .expect("This projection background process failed")
    });
```

**To Reproduce**
1. Start projection
2. Kill database (e.g delete/recreate the pod)
3. Observe that the `projector.run().await` never fails

### PR DESCRIPTION
**Pull request by to266**
Fixes #144 
Uses the first suggested solution by propagating the network error through the connection.

~~Will test in actual library that uses eventually-rs in a couple of hours, to see if this intrinsically solves the issue~~ Yes works

### CODE REVIEW

File: eventually-postgres/src/subscriber.rs [hunk 1]
```diff
@@ -23,20 +23,26 @@ use tokio_postgres::AsyncMessage;
...
+pub enum SubscriberError {
+    /// Error variant returned when deserializing payloads coming from Postgres' `LISTEN`
+    /// asynchronous notifications.
+    #[error("failed to deserialize notification payload from JSON: {0}")]
+    DeserializeError(String),
+
+    /// Error variant returned when the connection, used for `LISTEN` asynchronous notifications
+    /// gets dropped. Currently the subscriber cannot recover from this error and a new one should
+    /// be created.
+    #[error("postgres connection error: ${0}")]
```
Comment (ar3s3ru) [inline eventually-postgres/src/subscriber.rs:44]:
```suggestion
    #[error("postgres connection error: {0}")]
```
Why using `${0}`?

File: eventually-postgres/src/subscriber.rs [hunk 2]
```diff
@@ -23,20 +23,26 @@ use tokio_postgres::AsyncMessage;
...
+    ConnectionError(String),
```
Comment (ar3s3ru) [inline eventually-postgres/src/subscriber.rs:45]: Can we use `tokio_postgres::Error` here instead of `String`?

```suggestion
    ConnectionError(#[source] tokio_postgres),
```

File: eventually-postgres/src/subscriber.rs [hunk 3]
```diff
@@ -23,20 +23,26 @@ use tokio_postgres::AsyncMessage;
...
 /// Error returned by the `TryStream` on [`subscribe_all`]
-/// when deserializing payloads coming from Postgres' `LISTEN`
-/// asynchronous notifications.
 ///
 /// [`subscribe_all`]: struct.EventSubscriber.html#method.subscribe_all
 #[derive(Debug, Clone, thiserror::Error)]
-#[error("failed to deserialize notification payload from JSON: {message}")]
-pub struct DeserializeError {
-    message: String,
+pub enum SubscriberError {
```
Comment (ar3s3ru) [inline eventually-postgres/src/subscriber.rs:35]: If we have `SubscriberError`, we can remove the duplicated "Error" part from the enum variants:

```rust
pub enum SubscriberError {
    Deserialize(String),
    Connection(tokio_postgres::Error),
}
```

**Review by ar3s3ru — COMMENTED** [review]
Thanks for the PR :heart: 

Although I don't think this should be the end design, as I wrote on #144, we can merge this PR (when comments are addressed) to fix the bug. However, if you're still interested, I'd like to discuss and expand a better design approach on the original issue :smile:

File: eventually-postgres/src/subscriber.rs (hunk 2 above)
Comment (to266) [reply eventually-postgres/src/subscriber.rs:45]: `tokio_postgres` error is not `Clone`, and it needs to be `Clone` to send over the channel, as far as I can tell

Comment (ar3s3ru) [reply eventually-postgres/src/subscriber.rs:45]: Oh yes, indeed. Another "smell" of using a channel to send these values around 😅

**Comment by to266** [comment]
Addressed the comments :smiley: 

As far as #144 suggestion goes, I'm a fan of that! Right now it's a bit strange, as the background process starts when creating the subscriber, and until `subscribe_all` is invoked, I guess the channel simply fills with stuff... Moving this to `subscribe_all` makes it way more intuitive :+1: 

The only issue from my side right now is the lack of time for moving things along :wink:

**Review by ar3s3ru — APPROVED** [review]

**Comment by ar3s3ru** [comment]
@to266 glad to hear that! I will create a new issue (or use the new Discussions space) to keep digging at the design :+1:
